const nodemailer = require('nodemailer');
const { Pool } = require('pg');

exports.handler = async (event, context) => {
  // Only allow POST requests
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      body: JSON.stringify({ error: 'Method Not Allowed' }),
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS'
      }
    };
  }

  // Handle preflight OPTIONS request
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Headers': 'Content-Type',
        'Access-Control-Allow-Methods': 'POST, OPTIONS'
      }
    };
  }

  try {
    const { name, email, message } = JSON.parse(event.body);
    
    // Validate required fields
    if (!name || !email || !message) {
      return {
        statusCode: 400,
        body: JSON.stringify({ 
          success: false, 
          error: 'Missing required fields: name, email, and message are required' 
        }),
        headers: {
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*'
        }
      };
    }

    // Create database connection pool
    const pool = new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: { rejectUnauthorized: false }
    });

    // Create email transporter
    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST || 'smtp.gmail.com',
      port: process.env.EMAIL_PORT || 587,
      secure: false, // true for 465, false for other ports
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    // Format email content
    const date = new Date().toLocaleString();
    const emailBody = `
New Contact Form Submission

Name: ${name}
Email: ${email}
Message: ${message}
Submitted: ${date}

---
This message was automatically generated by your personal website contact form processor.
    `.trim();

    // Send email notification
    const emailInfo = await transporter.sendMail({
      from: process.env.EMAIL_FROM || process.env.EMAIL_USER,
      to: process.env.EMAIL_TO,
      subject: `New Contact Form Submission - ${new Date().toLocaleDateString()}`,
      text: emailBody,
      html: emailBody.replace(/\n/g, '<br>'),
    });

    console.log('Email notification sent successfully:', emailInfo.messageId);

    // Store message in Neon database
    let dbResult;
    try {
      dbResult = await pool.query(
        'INSERT INTO contact_messages (name, email, message, created_at) VALUES ($1, $2, $3, $4) RETURNING id',
        [name, email, message, new Date().toISOString()]
      );
      console.log('Message stored in database with ID:', dbResult.rows[0].id);
    } catch (dbError) {
      console.error('Failed to store message in database:', dbError);
      // Don't fail the entire request if database storage fails
      // Email was still sent successfully
    }

    // Close database connection
    await pool.end();

    return {
      statusCode: 200,
      body: JSON.stringify({ 
        success: true, 
        message: 'Contact form submitted successfully',
        messageId: emailInfo.messageId,
        storedInDatabase: !!dbResult
      }),
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      }
    };

  } catch (error) {
    console.error('Failed to process contact form:', error);
    
    return {
      statusCode: 500,
      body: JSON.stringify({ 
        success: false, 
        error: 'Failed to process contact form submission',
        details: process.env.NODE_ENV === 'development' ? error.message : 'Internal server error'
      }),
      headers: {
        'Content-Type': 'application/json',
        'Access-Control-Allow-Origin': '*'
      }
    };
  }
};
